export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD"
export const CHANGE_ERROR_STATUS = "CHANGE_ERROR_STATUS"

export const REQUEST_API_DATA_PENDING = "REQUEST_API_DATA_PENDING"
export const REQUEST_API_DATA_SUCCESS = "REQUEST_API_DATA_SUCCESS"
export const REQUEST_API_DATA_FAILED  = "REQUEST_API_DATA_FAILED"

 